config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :bookings
  get 'users/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :canchas do
    resources :reviews
  end
  resources :users
  root 'main#index'
  get 'main/index', to: 'main#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'mensajes/index'
  get 'mensajes/new'
  post 'mensajes', to: 'mensajes#create'
end

app/models/booking.rb
class Booking < ApplicationRecord
    validates :booked_for, numericality: { greater_than_or_equal_to: 1 }
end

app/controllers/bookings_controller.rb
require "json"
#require "rest-client"

class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  @@username = "uc_arriagada"
  @@password = "Z1noQlT21e"

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
    @canchas = Cancha.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
    @canchas = Cancha.all
    @users = User.all
    
    @validdatetime = @booking.booked_at.strftime("%Y-%m-%dT%H:%M:%SZ")
    location = "-33.49948202329449,-70.60769579870387"

    @token = get_collection

    @response = HTTParty.get("https://api.meteomatics.com/#{@validdatetime}/t_2m:C,weather_symbol_1h:idx/#{location}/json?access_token=#{@token}")
    @weather_symbol = @response["data"][1]["coordinates"][0]["dates"][0]["value"]
    @temperature = @response["data"][0]["coordinates"][0]["dates"][0]["value"]

    @weather = get_weather(@weather_symbol)

  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    @params = params[:id_court]
    @empty = '⠀⠀'

    @canchas = Cancha.all

    #@cancha_actual = @canchas.find(params[:id_court])
    # @params = params.require(:booking).permit(:id_court)
  end

  # GET /bookings/1/edit
  def edit
    @canchas = Cancha.all
    @users = User.all
    @empty = '⠀⠀'
    @params = @booking.id_court_id
  end


  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to booking_url(@booking), notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

      # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:id_user_id, :id_court_id, :booked_at, :booked_ends, :booked_for, :total_price, :bookingstatus)
    end

    def get_collection
      response = RestClient::Request.new(
        :method => :get,
        :url => "https://login.meteomatics.com/api/v1/token",
        :user => @@username,
        :password => @@password,
        :headers => { :accept => :json, :content_type => :json }
      ).execute
      results = JSON.parse(response.to_str)["access_token"]
    end

    def get_weather(weather_symbol)
      case weather_symbol
      when 1
        return "Clear"
      when 2
        return "Light clouds"
      when 3
        return "Partly cloudy"
      when 4
        return "Cloudy"
      when 5
        return "Rain"
      when 6
        return "Rain and snow / sleet"
      when 7
        return "Snow"
      when 8
        return "Rain shower"
      when 9
        return "Snow shower"
      when 10
        return "Sleet shower"
      when 11
        return "Light Fog"
      when 12
        return "Dense fog"
      when 13
        return "Freezing rain"
      when 14
        return "Thunderstorms"
      when 15
        return "Drizzle"
      when 16
        return "Sandstorm"
      end
    end
end

app/helpers/bookings_helper.rb
# frozen_string_literal: true

# Modulo de Bookings
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%if @booking.id_court_id != nil %>
    <% if current_user && current_user.admin or current_user && current_user.moderator %>
      <div class="field"> <%# Booked by %>
        <b>
        <h6> Hi Moderator! Please change what you need from booking of 
        <%= @canchas.find(@booking.id_court_id).nombre.capitalize() %>  
        made by user <%=@users.find(@booking.id_user_id).name.capitalize() %>
        </h6> 
        </b>
      </div>
    <%else%>
      <div class="field"> <%# Booked by %>
        <b>
        <h6> Hi <%= current_user.name %>! Please change what you need of your previous booking of 
        <%=@canchas.find(@booking.id_court_id).nombre %> </h6>
        </b>
      </div>
    <%end%>
  <%else%>
      <div class="field"> <%# Booked by %>
        <b>
        <h6> Hi <%=current_user.name%>! We're glad that your are making a booking of 
        <%=@canchas.find(@params).nombre%> with us </h6>
        </b>
      </div>
  <%end%>


  <%= form.label :id_user_id, @empty %> 
  <%= form.hidden_field :id_user_id, value: current_user.id %>  

  <%= form.label :id_court_id, @empty %> 
  <%= form.hidden_field :id_court_id, value: @params %> 

  <center>
  <% if current_user && current_user.admin or current_user && current_user.moderator %>
    <%= form.label :bookingstatus, "Booking Status" %> 
    <%= form.select :bookingstatus, options_for_select([['Approved'], ['Rejected']]), include_blank: true, prompt: '', style:"max-width: 30rem;"%> 
  <% else %> 
    <%if @booking.id_court_id != nil %>
      <h6> These were the options you selected </h6>
    <%end%>
    <%= form.label :bookingstatus, @empty %> 
    <%= form.hidden_field :bookingstatus, value: "Pending revision" %> 
  <%end%>
  </center>



  

  <%# selected: fue la única forma de setear los minutos siempre en 00  %>
  <%# desventaja es q la hora tmbn la deja como 00 al inicio %>
  <div class="field"> 
    <%= form.label :booked_at %>
    <%= form.datetime_select :booked_at, start_year: Date.today.year,
    discard_minute: true, selected: Date.tomorrow, 
    datetime_separator:" starting at ", start_hour: 8, end_hour: 20 %>
  </div>

  <%# prompt: 'Choose here :)' %>


  <%# <div class="field">
    <%= form.label :booked_ends %>
      <%# <%= form.datetime_select :booked_ends, discard_year: true, discard_month: true, discard_hour: true %> 
    <%# </div> %>


  <div class="field">
    <%= form.label :booked_for, "for a period of one hour you can enjoy yourself on the selected court" %>
    <%= form.hidden_field :booked_for, value: "1" %>
  </div> 

  <br>

  <div class="field">
    <h6> Total price: </h6>
    <h6> <%= form.label @canchas.find(@params).price %> CLP </h6>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/bookings/edit.html.erb
<center>

<% if current_user && current_user.admin or current_user && current_user.moderator %>
    <h1><b> Change a Booking </b></h1>
<% else%>
    <h1><b> Change your Booking </b></h1>
<%end%>

<%= render 'form', booking: @booking %>

<%= link_to 'Your Bookings', bookings_path, class:"btn btn-outline-primary"%> 
<%= link_to 'Booking Info', @booking, class:"btn btn-outline-primary" %>

app/views/bookings/index.html.erb
<center>
<h1><b>Bookings</b></h1>

<table class="table table-hover" style="max-width: 60rem;">
  <thead>
    <tr>
    <% if (current_user.admin or current_user.moderator)%>
      <th>Id User</th>
    <%end%>
      <th>Court</th>
      <th>Booked at</th>
      <th>Status</th>
      <%# <th colspan="3"></th>  %>
    </tr>
  </thead>


  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <%# ADMIN O MODERADOR PUEDEN VER TODO %>
        <% if (current_user.admin or current_user.moderator)%>
          <td><%= booking.id_user_id %></td>
          <td><%= @canchas.find(booking.id_court_id).nombre.capitalize %></td>
          <td><%= booking.booked_at.strftime("%Y-%m-%d, at %H") %></td>
          <td><%= booking.bookingstatus %></td> 
          <div class="btn-group" role="group">
            <td><%= link_to 'Show', booking, class:"btn btn-outline-info"%></td>
            <% if current_user && current_user.admin or current_user && current_user.moderator %>
              <td><%= link_to 'Edit', edit_booking_path(booking), class:"btn btn-outline-warning" %></td>
              <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger" %></td>
            <% end %>
          </div>
        <% else %> <%# SI ES QUE INGRESA UN USUARIO COMÚN LE MUESTRO SOLO SUS BOOKINGS! %>     
          <% if current_user.id == booking.id_user_id %>
            <td><%= @canchas.find(booking.id_court_id).nombre.capitalize %></td>
            <td><%= booking.booked_at.strftime("%Y-%m-%d, at %H") %></td>
            <td><%= booking.bookingstatus %></td>
            <div class="btn-group" role="group">
              <td><%= link_to 'Show', booking, class:"btn btn-outline-info"%></td>
              <% if current_user && current_user.admin or current_user && current_user.moderator %>
                <td><%= link_to 'Edit', edit_booking_path(booking), class:"btn btn-outline-warning" %></td>
                <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger" %></td>
              <% end %>
            </div>
            <% end %>
        <% end %>



      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%# <% if not (current_user && current_user.admin or current_user && current_user.moderator) %>
  <%# <%= link_to 'New Booking', new_booking_path, class:"btn btn-outline-primary" %>
<%# <% end %> 



<%= link_to 'Back to Home', "/", class:"btn btn-outline-primary" %>

app/views/bookings/new.html.erb
<center>

<h1><b>Make a Booking!</b></h1>

<%# P. IDENTIFICAR CANCHA QUE ESTAMOS ARRENDANDO %>
<%# para dsp poder devolverme a ESA cancha %>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', cancha_path(@params), class:"btn btn-outline-primary" %> 
<%= link_to 'Back to Courts', canchas_path, class:"btn btn-outline-primary" %>
<%# <%= link_to 'Your Bookings', bookings_path, class:"btn btn-outline-primary" %> 

app/views/bookings/show.html.erb
<center>


<%# <p>
  <strong>Id user:</strong>
  <%= @booking.id_user_id %> 
<%# </p> %>

<%if @booking.id_court_id != nil %>
  <% if current_user && current_user.admin or current_user && current_user.moderator %>
    <h1> <b> Booking of <%= @canchas.find(@booking.id_court_id).nombre.capitalize() %> </b></h1>
  <% else %>
    <h1> <b> This is your booking of <%= @canchas.find(@booking.id_court_id).nombre.capitalize() %> </b></h1>
  <%end%>
<%end%>


<% if current_user && current_user.admin or current_user && current_user.moderator %>
  <h6> made by user <%= @users.find(@booking.id_user_id).name %> </h6>
<%end%>


<br>

<h3> 
  <strong> Status:</strong>
  <%= @booking.bookingstatus %> 
</h3>


<h3>
  <strong>Booked at:</strong>
  <%= @booking.booked_at.strftime("%Y-%m-%d, at %H ") %>
</h3>

<h3>
  <strong> Weather:</strong>
  <%= @weather %> with a temperature of <%= @temperature %> °C
</h3>

<%# <h3>
  <strong>Booked ends:</strong>
  <%= @booking.booked_ends %>
<%# </h3> %> 
<br>

<% if current_user && current_user.admin or current_user && current_user.moderator %>
  <h6>
    Remember, to always resolve the "Pending revision" bookings.
  </h6>
<% else %>
  <h5>
    Remember, your bookings lasts <strong> <%= @booking.booked_for.to_s %> </strong> <strong> hour</strong>
  </h5>
  <h6> Make sure you see "Approved" on the Status field to know your request has been accepted. </h6>
  <br>
  <h6>
    Leave the court just as you found it, and inform at the beggining if anything is missing.
  </h6>
<% end %>

<br>

<%# <h3>
  <strong>Total price:</strong>
  <%= @booking.total_price %>
<%# </h3> %>



<br>

<%# <% if not (current_user && current_user.admin or current_user && current_user.moderator) %> 
<%# <% end %> 
<%= link_to 'Edit Booking', edit_booking_path(@booking), class:"btn btn-outline-primary" %> 
<%# <%= link_to 'Back to Bookings', bookings_path, class:"btn btn-outline-primary" %>
<%= link_to 'Back to Courts', canchas_path, class:"btn btn-outline-primary" %>