config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :bookings
  get 'users/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :canchas do
    resources :reviews
  end
  resources :users
  root 'main#index'
  get 'main/index', to: 'main#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'mensajes/index'
  get 'mensajes/new'
  post 'mensajes', to: 'mensajes#create'
end

app/models/cancha.rb
# frozen_string_literal: true

class Cancha < ApplicationRecord
  validates :nombre, :deporte, :estado, presence: true
  has_many :reviews, dependent: :destroy
end

app/controllers/canchas_controller.rb
# frozen_string_literal: true

# Controlador de la clase Canchas
class CanchasController < ApplicationController
  before_action :set_cancha, only: %i[show edit update destroy]

  # GET /canchas or /canchas.json
  def index
    @canchas = Cancha.all
    # Search for canchas by name
    @canchas = @canchas.where('nombre LIKE ?', "%#{params[:search]}%") if params[:search].present?
    # Order by order_by param and descendent
    @canchas = @canchas.order("#{params[:order_by]} ASC") if params[:order_by].present?
  end

  # GET /canchas/1 or /canchas/1.json
  def show
    @total_reviews = Review.where(cancha_id: @cancha).count
    @reviews = Review.where(cancha_id: @cancha).order('created_at DESC').max(5)
    @mean_score = Review.where(cancha_id: @cancha).average(:score)
  end

  # GET /canchas/new
  def new
    @cancha = Cancha.new
  end

  # GET /canchas/1/edit
  def edit; end

  # POST /canchas or /canchas.json
  def create
    @cancha = Cancha.new(cancha_params)

    respond_to do |format|
      if @cancha.save
        format.html { redirect_to cancha_url(@cancha), notice: 'Cancha was successfully created.' }
        format.json { render :show, status: :created, location: @cancha }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cancha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /canchas/1 or /canchas/1.json
  def update
    respond_to do |format|
      if @cancha.update(cancha_params)
        format.html { redirect_to cancha_url(@cancha), notice: 'Cancha was successfully updated.' }
        format.json { render :show, status: :ok, location: @cancha }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cancha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /canchas/1 or /canchas/1.json
  def destroy
    @cancha.destroy

    respond_to do |format|
      format.html { redirect_to canchas_url, notice: 'Cancha was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cancha
    @cancha = Cancha.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cancha_params
    params.require(:cancha).permit(:nombre, :deporte, :estado, :image_url, :price)
  end
end

app/helpers/canchas_helper.rb
# frozen_string_literal: true

# Canchas helper
module CanchasHelper
end

app/views/canchas/_form.html.erb
<%= form_with(model: cancha, local: true) do |form| %>
  <% if cancha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cancha.errors.count, "error") %> prohibited this cancha from being saved:</h2>

      <ul>
        <% cancha.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label "Name", class:"col-form-label mt-4" %>
    <%= form.text_field :nombre, class:"form-control", style:"max-width: 30rem;" %>
  </div>

  <div class="form-group">
    <%= form.label "Sport", class:"col-form-label mt-4" %>
    <%= form.select :deporte , options_for_select([['Tracks'], ['Soccer'], ['Tenis'], ['Volleyball'], ['Basquetball']]), include_blank: true, prompt: '', class:"form-control", style:"max-width: 30rem;" %>
  </div>

  <div class="form-group">
    <%= form.label "Status", class:"form-label mt-4" %>
    <%= form.select :estado, options_for_select([['Avaliable'], ['Occupied']]), include_blank: true, prompt: '', class:"form-control", style:"max-width: 30rem;" %>
  </div>

  <div class="form-group">
    <%= form.label "Rented by User", class:"form-label mt-4" %>
    <%= form.text_field :id_arrendatario, class:"form-control", style:"max-width: 30rem;" %>
  </div>

  <div class="form-group">
    <%= form.label "Price", class:"col-form-label mt-4" %>
    <%= form.text_field :price, class:"form-control", style:"max-width: 30rem;" %>
  </div>

  <div class="form-group">
    <%= form.label "Image URL", class:"form-label mt-4" %>
    <%= form.text_field :image_url, class:"form-control", style:"max-width: 30rem;" %>

  <br>
  
  <button type="submit" class="btn btn-primary">Submit</button>
<% end %>

app/views/canchas/edit.html.erb
<center>
<h1><b>Editing Court</b></h1>

<%= render 'form', cancha: @cancha %>
</center>
<br>

<%= link_to 'Back', canchas_path, class:"btn btn-outline-primary" %>

app/views/canchas/index.html.erb
<center>
<h1><b>Courts</b></h1>

<%= form_tag "/canchas", method: "GET" do %>
  <%= label_tag :search %>
  <%= text_field_tag :search, params[:search], class:"form-control",
   style:"max-width: 30rem;" %>
  <br>
  <%= label_tag :order_by %>
  <%= select_tag :order_by, options_for_select([["Name", "nombre"],
   ["Created at", "created_at"]], params[:order_by]), class:"form-select",
   style:"max-width: 30rem;" %>
  <br>
  <%= submit_tag "Search", class:"btn btn-info" %>
<% end %>


<table class="table table-hover" style="max-width: 50rem;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Sport</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @canchas.each do |cancha| %>
      <tr>
        <td><%= cancha.nombre %></td>
        <td><%= cancha.deporte %></td>
        <td><%= cancha.estado %></td>
        <div class="btn-group" role="group">
          <td><%= link_to 'Show', cancha , class:"btn btn-outline-info"%></td>
          <% if current_user && current_user.admin or current_user && current_user.moderator %>
            <td><%= link_to 'Edit', edit_cancha_path(cancha), class:"btn btn-outline-warning" %></td>
            <td><%= link_to 'Destroy', cancha, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger" %></td>
          <% end %>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>
</center>

<br>

<% if current_user && current_user.admin or current_user && current_user.moderator %>
  <%= link_to 'New Court', new_cancha_path, class:"btn btn-outline-primary" %>
<% end %>
<%= link_to 'Back', "/", class:"btn btn-outline-primary" %>

app/views/canchas/new.html.erb
<center>
<h1><b>New Court</b></h1>

<%= render 'form', cancha: @cancha %> 

<br>

</center>
<%= link_to 'Back', canchas_path, class:"btn btn-outline-primary" %>

app/views/canchas/show.html.erb
<center>
<h1> <b> Information of the court </b></h1>
<h2> <%= @cancha.nombre.capitalize() %> </h2>

<br>


<%# <h3>
  <strong>Name:</strong>
  <%= @cancha.nombre %>
<%# </h3> %>


<h3>
  <strong>Sport:</strong>
  <%= @cancha.deporte %>
</h3>

<%# <h3>
  <strong>Status:</strong>
  <%= @cancha.estado %>
<%# </h3> %>

<h3>
  <strong>Price:</strong>
  <%= @cancha.price %> CLP
</h3>


<h3>
  <strong>Score:</strong>
  <% if @mean_score %>
    <%= @mean_score.truncate(2) %>
  <% else %>
    No score yet
  <% end %>
</h3>

<% if @cancha.image_url %>
  <%= image_tag(@cancha.image_url, width: "30%") %> <br>
<% end %>

<p>
  <strong>Reviews (<%= @total_reviews %>)</strong>
  <%= render "reviews/review" %>
</p>
</center>

<% if current_user && current_user.admin or current_user && current_user.moderator %> 
  <%= link_to 'Edit', edit_cancha_path(@cancha), class:"btn btn-outline-primary" %>
<% end %>

<%= link_to 'Back to Courts', canchas_path, class:"btn btn-outline-primary" %>

<% if not (!current_user or  current_user && current_user.admin or current_user && current_user.moderator) %> 
    <%= link_to 'Book it!', new_booking_path(id_court: @cancha.id), class:"btn btn-outline-primary" %>
<% end %> 