config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :bookings
  get 'users/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :canchas do
    resources :reviews
  end
  resources :users
  root 'main#index'
  get 'main/index', to: 'main#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'mensajes/index'
  get 'mensajes/new'
  post 'mensajes', to: 'mensajes#create'
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to 'Home', root_path, class:'navbar-brand' %>
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
            <%= link_to 'Update Profile', edit_user_registration_path, class:'nav-link' %>
            <%= link_to 'Messages', mensajes_index_path, class:'nav-link' %>
            <%= link_to 'Bookings', bookings_path, class:'nav-link'%>
            <%= link_to 'End Session', destroy_user_session_path, method: :delete, class:'nav-link' %>
        <% else %>
            <%= link_to 'Sign up', new_user_registration_path, class:'nav-link' %>
            <%= link_to 'Log In', new_user_session_path, class:'nav-link' %>
        <% end %>
      </ul>
      <form class="d-flex">
        <% if current_user && current_user.admin %>
            </h4><%= link_to 'Admin Dashboard ', admin_root_path %></h4>
            <h4> Welcome Administrator <%= current_user.name.capitalize %></h4>
        <% elsif current_user && current_user.moderator %>
            <h4> Welcome Moderator <%= current_user.name.capitalize %></h4>
        <% elsif current_user %>
            <h4> Welcome <%= current_user.name.capitalize %>!</h4>
        <% else %>
            <h4> Welcome Guest!</h4>
        <% end %>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProyectoG57</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/index.html.erb
<h1>Hello, Rails!</h1>